name: Wie_is_de_mol
version: 1.0
main: nl.nilsrijkaart.widm.Main
api-version: 1.13
author: Nils Rijkaart
description: Wie is de Mol

commands:
  game:
    description: Start een nieuw spel
    usage: /<command>
    aliases: [widm, widmgame]
  gameutil:
    description: Ontvang game utils
    usage: /<command>
    aliases: [widmutil, widmgameutil]
  kleuren:
    description: Zie alle kleuren
    usage: /<command>
    aliases: [rollen, colors, roles]
  msg:
    description: msg command
    usage: /<command>
    aliases: [message, bericht, berichten, messages]